bad_words = ["dike", "goodpoop", "heroin", "juggs", "wazoo", "sexy", "lezbo", "fack", "v1gra", "erotism", "fuckup",
             "hore", "2g1c", "niggle", "ballbag", "vaginal", "jack-off", "balllicker", "jizim", "yellowman", "peck",
             "cocklicker", "palesimian", "nut sack", "cunts", "masterbat", "niggled", "bareback", "abortion",
             "sixtyniner", "badfuck", "sh!+", "jackoff", "dix", "cock snot", "kootch", "testis", "assbang", "doggin",
             "gringo", "slag", "sooty", "organ", "cockblocker", "how to murder", "cock pocket", "knob", "aeolus",
             "weenie", "ass hole", "fuck", "polack", "cockjockey", "titty", "assjacker", "gooks", "opium", "limy",
             "bootie", "datnigga", "pegging", "menstruate", "brown showers", "masterblaster", "penis", "gay sex",
             "dumb", "t1tt1e5", "swalow", "brotherfucker", "buttcheeks", "refugee", "camslut", "bum", "beer", "tang",
             "wanky", "mggor", "batty boy", "fags", "lucifer", "gaymuthafuckinwhore", "lezbian", "bangbros", "dildos",
             "wiseass", "asspirate", "kunnilingus", "macaca", "muff", "analprobe", "hooker", "dumass", "hoe",
             "pussy palace", "wang", "phukking", "fatah", "shitbrains", "minority", "destroy", "n1gger", "ejaculated",
             "footfucker", "nobhead", "carpetmuncher", "pube", "bull shit", "illegal", "pimpsimp", "bullturds",
             "cummin", "heterosexual", "cyberfucked", "wh0re", "motherfucka", "nad", "nads", "ejaculate", "camgirl",
             "piss pig", "radicals", "coitus", "tranny", "pussylips", "lusty", "nastyslut", "phone sex", "cherrypopper",
             "inbred", "dickhead", "foot fetish", "butt plug", "s_h_i_t", "kock", "erect", "slutt", "dickhole",
             "eat a dick", "peyote", "punta", "scrote", "son-of-a-bitch", "dumb ass", "groe", "reefer", "analannie",
             "homoerotic", "fxck", "kooches", "two girls one cup", "nigr", "penisfucker", "asses", "fetish", "porno",
             "fingerfucker", "tittie5", "bitcher", "feltching", "dickweed", "fistfucker", "shitbag", "twat",
             "shaved beaver", "slaughter", "dick-ish", "ma5terb8", "foreskin", "coochy", "jiz", "niggers", "sexfarm",
             "libido", "pi55", "killer", "assjockey", "cummer", "son of a bitch", "chota bags", "nob", "fucktwat",
             "slutwear", "tittie", "lovemaking", "shitty", "shitbreath", "molestor", "dickwad", "asslick",
             "bust a load", "niggaz", "snigger", "bitched", "fuckknob", "beaver", "pooping", "tushy", "boooobs",
             "w00se", "panti", "wog", "lube", "muther", "butthead", "shag", "coondog", "splooge", "japcrap",
             "white power", "t1tties", "fuq", "screwed", "porchmonkey", "breastman", "pocha", "burn", "dahmer",
             "titjob", "bitchy", "wankjob", "dopey", "fucknut", "naked", "herp", "propaganda", "pendy", "amateur",
             "dumbfuck", "skankbitch", "enlargement", "potty", "buttfuck", "flasher", "homo", "baptist", "dickheads",
             "cocktail", "cyberfucking", "hentai", "dick", "fuck-ass", "raghead", "homicide", "whitey", "doosh", "butt",
             "nlggor", "ball kicking", "fisty", "conspiracy", "double dong", "clamdigger", "souse", "b17ch",
             "loverocket", "beastial", "nutsack", "neonazi", "mufflikcer", "sodomy", "sexhouse", "bowels", "titfucker",
             "sexymoma", "alabama hot pocket", "dummy", "perversion", "gubba", "cervix", "lameass", "spit", "nutfucker",
             "scallywag", "s&m", "asshopper", "crackpipe", "pudd", "pimpjuic", "motherfucks", "cumfest", "penises",
             "copulate", "dicklick", "racy", "nipplering", "darky", "dick shy", "pissoff", "ontherag", "bimbos",
             "b!tch", "nambla", "mutha", "bummer", "assassin", "assholes", "gae", "evl", "communist", "luckycammeltoe",
             "moky", "limey", "cyberslimer", "baby batter", "bollock", "whoar", "tuckahoe", "sodomise", "futanari",
             "deep throat", "heshe", "dicklicker", "boob", "lezbe", "whigger", "twunter", "satan", "anal", "sleezebag",
             "yobbo", "bitch tit", "pedophilia", "ecchi", "buggery", "p0rn", "sucking", "cocksuckers", "shithappens",
             "sodomite", "husky", "fuckface", "rapist", "jagoff", "niggor", "pistol", "dingleberries", "muthafuckaz",
             "bampot", "backdoorman", "pussylicker", "primetime", "mad", "sextogo", "apeshit", "middle finger",
             "muthafecker", "crotch", "nude", "bigbutt", "mothafucka", "devil", "he-she", "scroat", "ecstacy",
             "crotchjockey", "retarded", "lapdance", "fuckin", "rapey", "shitcanned", "gonorrehea", "mocky", "sexwhore",
             "damned", "gey", "greaseball", "pillowbiter", "stroking", "nig-nog", "williewanker", "blow mud",
             "fucktards", "shhit", "shirt lifter", "arabs", "crapola", "sumofabiatch", "undressing", "dumbbitch",
             "arian", "dickbrain", "gangbanger", "teets", "cockmonkey", "rearentry", "extasy", "coon", "toke", "vixen",
             "bdsm", "cockmunch", "cumslut", "intheass", "areola", "bomd", "cum guzzler", "fister", "fucktoy",
             "whorebag", "butt-pirate", "fuckina", "dickzipper", "cacker", "lsd", "footfuck", "mcfagget", "pedophile",
             "feces", "muthafuckker", "flydye", "zipperhead", "cumguzzler", "threeway", "assfukka", "bint",
             "smackthemonkey", "cocknugget", "nonce", "menstruation", "clit licker", "freex", "clogwog", "tit wank",
             "autoerotic", "faith", "crotte", "asskiss", "cunilingus", "kaffre", "leather straight jacket", "shiz",
             "c.o.c.k.", "horney", "beat-off", "iberian slap", "bullshitted", "pooperscooper", "ball licking",
             "cocksuck", "ghey", "darkie", "vietcong", "shit ass", "jiggabo", "beatch", "cocksmoker", "barely legal",
             "titfuckin", "bullshit", "poontang", "masterbat3", "nut butter", "gaydo", "motherfucker", "hotdamn",
             "fuuck", "puntang", "fuck hole", "bosomy", "master-bate", "gonads", "suckme", "terror", "sadist",
             "shitspitter", "mong", "premature", "freakyfucker", "omorashi", "mickeyfinn", "whit", "ikey",
             "mothafucking", "buttmuncher", "moslem", "unclefucker", "dp action", "trojan", "jerked", "vulgar",
             "booooooobs", "masochist", "bible", "c-o-c-k", "cunnie", "cunn", "pissin", "shitting", "pissed", "triplex",
             "goyim", "pastie", "geez", "cnut", "ass fuck", "bomb", "hoar", "bunga", "ball gag", "redneck",
             "tunneloflove", "motherfuckin", "boners", "rectal", "renob", "fucks", "trumped", "slutdumper", "faig",
             "lezzy", "clitfuck", "peepee", "ass-hat", "sos", "hijack", "hork", "gayass", "mutherfucker", "mthrfucking",
             "d1ldo", "fckcum", "testicles", "slutkiss", "leather restraint", "cyberfuck", "fartknocker", "vatican",
             "veqtable", "fuckit", "goddamnmuthafucker", "kumming", "pedophiliac", "jesuschrist", "nastybitch",
             "manhater", "mothafuckaz", "coonnass", "jap", "assbag", "gob", "nig", "scrotum", "c0cksucker", "handjob",
             "bitchin", "horseshit", "headfuck", "fistfucks", "niggah", "wedgie", "slavedriver", "rumprammer", "junkie",
             "carruth", "swallower", "ejaculating", "tortur", "shittiest", "vajayjay", "birdlock", "doofus",
             "sweetness", "spunky", "panty", "suicide", "buttbang", "farty", "blonde action", "orgasm", "bitching",
             "vag", "lubejob", "gaylord", "abbo", "beaner", "athletesfoot", "hummer", "honky", "sonofabitch",
             "assbanger", "knife", "feck", "cockmongler", "mulatto", "beardedclam", "p.u.s.s.y.", "shitoutofluck",
             "blackman", "cameltoe", "stroke", "lactate", "frigg", "prostitute", "domination", "corruption",
             "trisexual", "pleasure chest", "hooch", "faggitt", "willy", "blow your load", "dragqween",
             "shitblimp", "ar5e", "cocklover", "jesus", "raped", "a_s_s", "cocky", "lickme", "fudge-packer", "bugger",
             "italiano", "masterbate", "sandler", "stripclub", "gangbanged", "frigga", "shitheads", "hoes", "hoor",
             "anilingus", "niggur", "cock sucker", "jerk", "cameljockey", "conservative", "jigg", "hymie", "chinky",
             "fisting", "skeet", "jizzum", "shitter", "jiggy", "tard", "axwound", "knobend", "dirsa", "fatso", "whore",
             "anal impaler", "cokmuncher", "gyp", "slopy", "pussi", "dykes", "dripdick", "kwif", "dog style", "fecker",
             "foobar", "latin", "pearlnecklace", "milf", "cuntlick", "pissing", "jail bait", "paddy", "hot carl",
             "suckmyass", "inthebuff", "nob jokey", "meatbeatter", "pussie", "fastfuck", "jebus", "fucck", "hamas",
             "holy shit", "fukker", "alaskan pipeline", "remains", "gokkun", "omg", "pohm", "b1tch", "sandm",
             "cocksucker", "swallow", "sexed", "puke", "footjob", "toots", "mr hands", "bukkake", "orgy", "fook",
             "hodgie", "bimbo", "d1ld0", "assnigger", "deggo", "fuckwad", "lezzie", "cancer", "ugly", "lusting",
             "timbernigger", "nuke", "spade", "ritard", "cunntt", "big tits", "stoned", "taig", "teez", "horn", "nigga",
             "knobjokey", "pimp", "gyppy", "incest", "dickmilk", "funfuck", "holestuffer", "motherfuckers",
             "homosexual", "bootycall", "bondage", "guido", "blow me", "teabagging", "minge", "pollock", "peni5",
             "fuckhole", "dommes", "pimpjuice", "asshead", "negro", "sh!t", "lesbian", "nudity", "cornhole", "slut",
             "niggaracci", "hindoo", "slapper", "nigre", "servant", "spermacide", "humping", "fuckwhore", "style doggy",
             "dickfuck", "bastard", "daterape", "bi-sexual", "pimper", "pros", "mafugly", "spermhearder", "humped",
             "tawdry", "hosejob", "desire", "skag", "phonesex", "hymen", "f_u_c_k", "squaw", "god-dam", "boang",
             "dickforbrains", "fondle", "ovums", "a$$hole", "jew", "hoer", "phungky", "titwank", "jiga", "sniggering",
             "cum", "duche", "weiner", "nastyho", "shite", "bung hole", "muffdiver", "goddamn", "shitforbrains",
             "bitchtits", "poonani", "feltcher", "assmonkey", "hootch", "shi+", "spik", "livesex", "booze", "pu55y",
             "homobangers", "big breasts", "skankwhore", "pinko", "blonde on blonde action", "fatass", "assbandit",
             "analsex", "blow your l", "pudboy", "brassiere", "pimped", "pornos", "v14gra", "hook", "nignog", "dirty",
             "gangbangs", "cocain", "godamn", "jerkoff", "moolie", "pecker", "venus mound", "butt fuck", "protestant",
             "scantily", "balls", "fok", "shinola", "pom", "nipples", "injun", "sleaze", "god damn", "douchewaffle",
             "pussys", "pisspig", "cuntface", "negros", "samckdaddy", "pickaninny", "sand nigger", "orgasims", "coons",
             "snowballing", "playboy", "sexhound", "kyke", "radical", "strap on", "bestial", "whiskeydick", "ginzo",
             "dickwod", "frotting", "gypp", "nookey", "junky", "vibrator", "sixtynine", "cut rope", "viagra",
             "cuntlicking", "douchebags", "dragqueen", "sadis", "chodes", "hell", "big black", "kinky", "boobies",
             "asswipe", "wetb", "fellatio", "firing", "gatorbait", "kondum", "busty", "punani", "donkey punch",
             "shithole", "fuckinright", "fatfucker", "fanyy", "clusterfuck", "cockbite", "fannybandit", "cocksucked",
             "cunt-struck", "choc ice", "nigra", "muff diver", "fag", "hemp", "whiskey", "dumbass",
             "masterbation", "auto erotic", "tittywank", "horny", "taff", "taste my", "mothafuckings", "mooncricket",
             "violet blue", "bullet vibe", "shitings", "hobo", "asswipes", "lmfao", "paki", "jerkass", "fuker",
             "escort", "shitola", "bumblefuck", "vodka", "getiton", "slimebucket", "smegma", "snot", "eat my ass",
             "pron", "fuckyou", "whop", "fourtwenty", "porn", "buttpirate", "fuckoff", "nofuckingway", "faggot",
             "pornography", "girl on top", "phuq", "eatballs", "assault", "clamdiver", "sexpot", "doublelift",
             "barface", "crapper", "wab", "commie", "mideast", "cuntsucker", "soused", "turd", "douchebag",
             "cuntfucker", "nigger", "dumbshit", "niggardliness", "gaywad", "hijacker", "sniper", "gangsta",
             "ejaculates", "foad", "gypo", "punky", "hiscock", "shemale", "meth", "sexo", "dvda", "coksucka",
             "assassination", "snatch", "dyefly", "ethical slut", "jewish", "slideitin", "f u c k e r", "nimrod",
             "hom0", "bi curious", "xtc", "boonie", "shitass", "upthebutt", "a54", "s-h-1-t", "cumjockey", "knobbing",
             "bitches", "cooly", "gaytard", "pimpis", "fagging", "twathead", "trailertrash", "dicks", "bigtits",
             "sleezeball", "girls gone wild", "breastjob", "shited", "weapon", "bazooms", "drug", "muffdiving",
             "dendrophilia", "leper", "junglebunny", "lingerie", "titlover", "krap", "spick", "g-spot", "faggots",
             "assfucker", "sex", "cripple", "fingerfucked", "twatty", "butthole", "boom", "spermherder", "nymphomania",
             "cock", "kissass", "pee", "fcuker", "scat", "extacy", "mofo", "dickflipper", "facial", "butchdyke",
             "jerk off", "tubgirl", "fisted", "kum", "turnon", "beatyourmeat", "knobjocky", "taking the piss",
             "buttmunch", "bra", "niggards", "slopehead", "whoralicious", "necro", "dickdipper", "stfu", "muffdive",
             "diddle", "wetback", "gotohell", "stringer", "blowjobs", "clunge", "mastabater", "how to kill",
             "reverse cowgirl", "poop", "fuckpig", "sexing", "nappy", "splooge moose", "piss", "towelhead", "lezz",
             "lezbefriends", "byatch", "phuck", "n1gga", "ghay", "a2m", "abo", "pud", "lovegoo", "babies", "lesbayn",
             "lardass", "killed", "syphilis", "fatfuck", "cumshots", "booby", "doggiestyle", "foursome", "masturbating",
             "sheeney", "zoophilia", "kunja", "tongue in a", "tribadism", "double penetration", "spigotty", "hostage",
             "mothafuck", "canadian", "t1t", "urophilia", "bunny fucker", "shaved pussy", "floo", "purinapricness",
             "skumbag", "ejaculatings", "yankee", "gippo", "cockknoker", "porch monkey", "sandnigger", "fuck trophy",
             "twatwaffle", "thug", "aryan", "buttmuch", "fingerfood", "ruski", "a$$", "cumquat", "shit", "slutty",
             "lezzies", "clitty litter", "abuse", "bisexual", "geni", "steamy", "nsfw images", "kunt", "shitey",
             "moles", "pubes", "niger", "cockburger", "dumbasses", "backdoor", "bone", "shitcan", "jaggi", "goddamned",
             "fcuking", "titfuck", "ginger", "hitler", "sniggers", "bigass", "women rapping", "sanger", "spooge",
             "tw4t", "bloody", "dick-sneeze", "blow j", "fornicate", "chinamen", "gai", "freakfuck",
             "rosy palm and her 5 sisters", "assclown", "killing", "lugan", "suck", "c-u-n-t", "godsdamn", "minger",
             "titbitnipply", "asshole", "goddammit", "s0b", "fuckher", "zoophile", "banging", "donkeyribber", "smutty",
             "chickslick", "henhouse", "suckoff", "valium", "sluts", "pantie", "rabbi", "dirty sanchez", "tarbaby",
             "trots", "drunken", "fore", "essohbee", "vibrater", "munter", "european", "moneyshot", "skankfuck",
             "mound of venus", "cok", "shitters", "kike", "kraut", "nigg4h", "bulldike", "tinkle", "suicide girls",
             "dickface", "sexkitten", "jimfish", "bong", "hand job", "slutbag", "negroes", "motherfuckka", "dive",
             "mof0", "ball gravy", "mormon", "buttplug", "pindick", "deposit", "shoot", "a55hole", "jerk-off",
             "hardcoresex", "fungus", "vulva", "jailbait", "make me come", "opiate", "motherfuck", "ejaculation",
             "niggard", "asspuppies", "jungle bunny", "footlicker", "flaps", "cocknose", "rtard", "beaners", "buried",
             "queers", "shat", "bigger", "wrinkled starfish", "footstar", "two fingers", "angie", "nawashi", "buttface",
             "tantra", "pussy", "ponyplay", "pussycat", "fux", "krappy", "cunteyed", "herpy", "sodomize", "slope",
             "gonzagas", "prude", "peehole", "arse", "slutting", "lezzo", "dogging", "fuck-tard", "assface", "creampie",
             "doo-doo", "oral", "bumclat", "knob end", "died", "kummer", "cuntass", "tosser", "showtime", "flange",
             "cox", "loadedgun", "punany", "santorum", "nipple", "playgirl", "cock-sucker", "asscock", "doggie-style",
             "dago", "hoare", "argie", "d0uche", "nip", "sexslave", "asshore", "dicksucker", "tonguetramp", "pussies",
             "perv", "snowback", "chinese", "pansies", "mother fucker", "d0ng", "hookers", "teste", "s-o-b",
             "ball sucking", "munt", "jock", "fuckmonkey", "bumfuck", "gspot", "rubbish", "nazism", "fucker", "panties",
             "boozy", "jigga", "female squirting", "gfy", "murder", "niggles", "bollick", "bulldyke", "cockrider",
             "shitted", "barfface", "arab", "ball sack", "revue", "thirdeye", "girls", "s hit", "piss-off", "barenaked",
             "bitchslap", "fingerfuck", "rusty trombone", "dick hole", "fagot", "whored", "assranger", "peepshow",
             "pornking", "hooter", "sucker", "mtherfucker", "nastywhore", "ejakulate", "gaysex", "jihad", "numbnuts",
             "hotpussy", "eat hair pie", "semen", "backseat", "dego", "booty call", "swinger", "dillweed", "fuckings",
             "sultry women", "spiks", "cuntlicker", "shibari", "ballsack", "blue waffle", "camwhore", "mothafucks",
             "urinate", "raging boner", "dolcett", "sh1t", "chesticle", "russki", "m-fucking", "va-j-j", "boned",
             "fuckboy", "womb", "fistfuck", "butt-fuck", "motherfucked", "cocklump", "assklown", "ahole", "whiskydick",
             "felching", "golden shower", "wuss", "waysted", "bountybar", "rimjaw", "cyberfuckers", "moo moo foo foo",
             "urine", "pussypounder", "honger", "hotsex", "transexual", "cocktease", "scissoring",
             "gtfo", "x-rated", "kaffir", "homodumbshit", "masterbating", "kumquat", "gooch", "dickman", "insest",
             "felch", "phuked", "assmuncher", "douchey", "dickslap", "gayfuck", "reetard", "suckass", "sandbar",
             "assbangs", "kumbubble", "dickripper", "prickteaser", "hard core", "huge fat", "dog-fucker", "mothafuckas",
             "clitface", "coochie", "jelly donut", "niggardly", "assgoblin", "buttman", "motherfuckings", "genitals",
             "weirdo", "bawdy", "schlong", "spook", "godammit", "fubar", "arsehole", "facefucker", "kill", "nittit",
             "wiseasses", "whoreface", "bunghole", "screwyou", "coffin dodger", "voyeur", "muncher", "l3i+ch",
             "fuckhead", "stagg", "goddam", "rectus", "cockfucker", "violet wand", "doggie style", "loin", "assshole",
             "israel", "how to murdep", "blumpkin", "suckmydick", "nigg", "creamy", "flydie", "sucks", "gyppie",
             "group sex", "wet dream", "bum boy", "breeder", "bitchass", "cum freak", "heeb", "piky", "strapon",
             "goddamnit", "nookie", "sexually", "dirty pillows", "queerhole", "cocknob", "cyberfuc", "dookie", "usama",
             "jijjiboo", "cums", "dumbcunt", "cunt", "homoey", "rum", "hoser", "flog the log", "goldenshower", "rere",
             "lesbos", "harem", "tnt", "klan", "mick", "assh0le", "rearend", "bloodclaat", "masturbation", "cocksucer",
             "goatcx", "tongue", "hitlerism", "pikey", "cocks", "fairies", "whitetrash", "sambo", "diligaf", "rigger",
             "whites", "coprophilia", "femdom", "nigg3r", "cumqueen", "manpaste", "whoring", "niggardlinesss",
             "god-damned", "skullfuck", "pisshead", "dlck", "erotic", "cocksniffer", "pissers", "torture", "c.0.c.k",
             "marijuana", "farting", "reich", "gonad", "cumstain", "orga", "nymph", "pubiclice", "fistfuckers",
             "blowjob", "butt-fucker", "enema", "mockey", "asswhore", "forni", "l3itch", "pussyeater", "bowel",
             "xrated", "cunnilingus", "fukkin", "shitlist", "payo", "bollok", "urinal", "rump", "lesbo", "scrot",
             "assman", "weed", "pedo", "sextoys", "penisbanger", "strappado", "yaoi", "cockeye", "nig nog", "git",
             "azazel", "child-fucker", "fuks", "fux0r", "fuk", "banger", "gang bang", "tart", "booooobs", "fuckass",
             "puddboy", "asshat", "cockwaffle", "butt-fuckers", "cocksmith", "damnation", "hardon", "assho1e",
             "one cup two girls", "dipship", "queero", "throating", "bombing", "dixiedyke", "lynch", "bitchers",
             "republican", "kums", "pissflaps", "pthc", "period", "dyke", "lech", "threesome", "gash", "pawn", "titi",
             "spankthemonkey", "cocksmoke", "goatse", "fistfucking", "fannyflaps", "giant cock",
             "son of a motherless goat", "cunthole", "slave", "fingerbang", "dickless", "poof", "window licker",
             "pee-pee", "fuckersucker", "pussy fart", "hitlerist", "mattressprincess", "pixie", "pixy", "shithead",
             "grope", "lez", "cybersex", "quickie", "chav", "shitface", "wanking", "uterus", "ma5terbate", "spig",
             "slav", "jack off", "upskirt", "fagots", "cocksucking", "molest", "bang", "screw", "shithouse",
             "flatulence", "japs", "harder", "redlight", "c0ck", "fuck puppet", "fuckfreak", "grostulation",
             "mothafucker", "cockfight", "penile", "shota", "yiffy", "bastinado", "twobitwhore", "circlejerk",
             "queerbait", "ass-pirate", "welfare", "booobs", "assbanged", "welcher", "fuckmeat", "buggered", "seamen",
             "seduce", "titt", "stiffy", "dipstick", "womens", "beaver cleaver", "honkey", "dimwit", "uck", "fart",
             "faggit", "liberal", "peepshpw", "hottotrot", "jizm", "mockie", "muffindiver", "bootee", "looney", "hussy",
             "thicklips", "tainted love", "penthouse", "hiv", "testes", "seaman", "fuckwit", "pasty", "glazeddonut",
             "f4nny", "fecal", "cooter", "asspacker", "shav", "chin", "cyalis", "lezza", "bogan", "wuzzie", "crap",
             "cipa", "climax", "lmao", "fuckbutter", "felatio", "masterb8", "ninny", "death", "golliwog", "lovejuice",
             "titties", "fuckwitt", "koon", "sextoy", "s-h-i-t", "asswad", "shitstain", "date rape", "old bag",
             "spaghettinigger", "dicktickler", "pole smoker", "yid", "willie", "ass-fucker", "dickbag", "nobjocky",
             "reestie", "choad", "5hit", "breast", "skanky", "buttstain", "fuckedup", "uptheass", "crikey",
             "doggy style", "pooper", "spermbag", "roach", "hobag", "boink", "doodoo", "whash", "fingerfucks",
             "fuckheads", "shittings", "pisses", "skank", "thrust", "taboo", "lovemuscle", "fairy", "splittail", "darn",
             "jiggerboo", "c-0-c-k", "rimjob", "fuck yo mama", "m0f0", "chink", "guro", "kigger", "doom", "camel toe",
             "jizzed", "bollocks", "cop some wood", "sodom", "boody", "fight", "loins", "tush", "one guy one jar",
             "sperm", "slimeball", "ra8s", "kinbaku", "kills", "spread legs", "nudger", "fukkers", "terd",
             "masterbations", "assblaster", "psycho", "buttfucker", "vibr", "bombs", "acrotomophilia", "angry",
             "punanny", "hijacking", "beotch", "breasts", "gassy ass", "jism", "fenian", "assbite", "givehead",
             "niggling", "brea5t", "fuckable", "blow", "puto", "knobhead", "douche", "smartass", "yeasty",
             "pussyfucker", "explosion", "gross", "slut bucket", "cockholster", "shittier", "peckerhead",
             "dawgie-style", "poopchute", "gender bender", "pubic", "niggas", "phuk", "lovebone", "pusy", "whorefucker",
             "asssucker", "penetrate", "doggystyle", "bullshits", "ham flap", "booty", "slanteye", "herpes",
             "cockmuncher", "mosshead", "stupidfuck", "tittyfucker", "condom", "fucktard", "wad", "niggerhole",
             "rape", "b00bs", "ass", "urethra play", "fuckbag", "nutter", "phallic", "floozy", "buttfucka", "bi+ch",
             "coolie", "defecate", "sissy", "sausage queen", "puss", "h0mo", "foah", "demon", "orally", "faeces",
             "loser", "fuckbuddy", "funeral", "sod off", "beaver lips", "zubb", "wetspot", "assshit", "boozer",
             "gaybob", "crabs", "murderer", "deapthroat", "clits", "c.u.n.t", "skankywhore", "cracker", "terrorist",
             "sick", "cockblock", "cuntbag", "freefuck", "devilworshipper", "kink", "fuckstick", "assmunch", "assfuck",
             "genital", "queaf", "israeli", "wtf", "strip", "shortfuck", "fuckbrain", "faigt", "mastrabator",
             "male squirting", "cyberfucker", "mams", "whorehouse", "quim", "shrimping", "chinc", "asscowboy",
             "cockcowboy", "ovary", "gook", "rentafuck", "cretin", "wop", "retard", "negroid", "rosy palm", "cocksman",
             "toilet", "cunthunter", "spunk", "cumming", "son of a whore", "chick with a dick", "shitfit", "smeg",
             "j3rk0ff", "babe", "lesbians", "dipshit", "farted", "anal leakage", "bicurious", "cum dumpster", "fat",
             "dead", "molester", "godamnit", "xxx", "twunt", "jackshit", "spank", "dickjuice", "fellate",
             "virginbreaker", "dry hump", "niggarding", "mothafuckers", "octopussy", "attack", "fagbag", "russkie",
             "chocolate rosebuds", "pussylover", "lezbos", "bestiality", "popimp", "kumbullbe", "magicwand", "chincs",
             "cunt hair", "whores", "pisser", "motherfucking", "dickwhipper", "fucknugget", "bazongas", "jackasses",
             "wanker", "boner", "goy", "orgasim", "tits", "bohunk", "phuking", "sadom", "panooch", "vjayjay",
             "alligatorbait", "sonofbitch", "mothafucked", "hun", "nooner", "faggs", "d1ck", "fuckwhit", "poverty",
             "shitcunt", "fuck you", "midget", "shamedame", "fuckingshitmotherfucker", "big knockers", "bast", "4r5e",
             "shitt", "gays", "lust", "r-tard", "smack", "asian", "cocksukka", "scrud", "biteme", "penetration", "a55",
             "phukked", "aroused", "thirdleg", "deepthroat", "bookie", "smut", "scag", "cuntslut", "penial", "osama",
             "crappy", "woody", "transsexual", "cunny", "niggerhead", "doggy-style", "piccaninny", "goregasm",
             "paedophile", "twink", "dingleberry", "cockmaster", "smartasses", "boong", "pric", "queer", "clitorus",
             "hard on", "prod", "bitch", "corksucker", "shiznit", "moron", "jackhole", "easyslut", "shits",
             "spreadeagle", "azz", "fucka", "addict", "fuckmehard", "napalm", "dicksipper", "gipp", "poopuncher",
             "shitfaced", "unfuckable", "orgasms", "fagg", "goddamit", "shithapens", "assbagger", "fuckfriend",
             "jerk0ff", "fagfucker", "twinkie", "need the dick", "nooky", "penispuffer", "fukwhit", "kanake", "geezer",
             "dingle", "shitbagger", "trashy", "he11", "mastabate", "mothafuckin", "beeyotch", "gyppo", "poop chute",
             "fuckfest", "testicle", "yellow showers", "fingering", "drunk", "nazi", "flamer", "juggalo", "dixiedike",
             "pms", "lotion", "piker", "beater", "asslover", "dope", "fleshflute", "caca", "fucknutt", "goddamnes",
             "nimphomania", "stupidfucker", "chode", "wank", "maxi", "boobs", "fuck buttons", "pubis", "tities",
             "idiot", "cockmongruel", "shitfucker", "tittiefucker", "willies", "buttfuckers", "clitty", "doochbag",
             "racist", "headlights", "israels", "bigbastard", "testical", "kotex", "picaninny", "cahone", "shitdick",
             "fuckinnuts", "polesmoker", "asskisser", "eatpussy", "lovegun", "crotchrot", "snuff", "asswhole",
             "cockshit", "beastiality", "felcher", "jizz", "slime", "iap", "molestation", "homey", "scum", "fuckbutt",
             "munging", "niggarded", "pedobear", "eunuch", "fuck-bitch", "spic", "motherlovebone", "coital", "cumdump",
             "fugly", "failed", "d0uch3", "vagina", "jacktheripper", "fistfucked", "muff puff", "s.h.i.t.", "tit",
             "orgies", "shit fucker", "snatchpatch", "gang-bang", "m0fo", "booger", "cra5h", "clover clamps", "gigolo",
             "teat", "cuntfuck", "gun", "ethiopian", "queef", "pu55i", "cl1t", "fannyfucker", "cocaine",
             "cleveland steamer", "cockknocker", "lesbain", "choade", "kinkster", "uzi", "meatrack", "jugs", "piss off",
             "cohee", "shaggin", "biatch", "damn", "narcotic", "assfaces", "whiz", "kunilingus", "cuntsicle",
             "dickbeaters", "ribbed", "gummer", "shitfuck", "fuckingbitch", "skankybitch", "mthrfucker", "cumdumpster",
             "jade", "shooting", "bastardo", "dickish", "jigaboo", "hot chick", "titlicker", "shiting", "lemon party",
             "baby juice", "brunette action", "pussylicking", "kkk", "scrog", "crack-whore", "mgger", "horniest",
             "coprolagnia", "lolita", "sniggered", "wh0reface", "fear", "dildo", "noonan", "piece of shit", "fukwit",
             "barelylegal", "cumtart", "whacker", "whorealicious", "butchdike", "honkers", "slutwhore", "beef curtain",
             "fucked", "randy", "virgin", "blow job", "two fingers with tongue", "sexy-slim", "bitchez", "wigger",
             "vorarephilia", "butt-bang", "menage a trois", "raping", "twats", "prick", "brothel", "kafir", "robber",
             "knobed", "violence", "prickhead", "bod", "dagos", "sixsixsix", "pcp", "arrse", "asslicker", "fvck",
             "undies", "interracial", "fanny", "ethnic", "shawtypimp", "hooters", "twatlips", "assassinate", "chinaman",
             "limpdick", "tittyfuck", "hump", "glans", "nobjokey", "hebe", "menses", "fingerfuckers", "kawk", "topless",
             "honk", "quicky", "testee", "vomit", "cumm", "ovum", "looser", "barf", "dickfucker", "suckmytit", "cawk",
             "sexual", "douche-fag", "lowlife", "erection", "tub girl", "bellend", "jiggaboo", "excrement",
             "muthrfucking", "thundercunt", "peckerwood", "spac", "bloody hell", "sob", "5h1t", "anus", "wench",
             "black cock", "fagged", "dicksucking", "fudgepacker", "deth", "dammit", "nympho", "tied up", "bodily",
             "kaffer", "pocho", "jackass", "pornflick", "cumbubble", "bullcrap", "skinflute", "failure", "faggotcock",
             "fingerfucking", "fucktart", "gay", "hardcore", "fuckme", "bastards", "licker", "pot", "tramp", "lezbians",
             "beastality", "cockqueen", "fistfuckings", "poorwhitetrash", "zigabo", "schizo", "weewee", "hillbillies",
             "pommy", "pust", "nook", "cockface", "stupid", "poonany", "2 girls 1 cup", "strip club", "japanese",
             "douch3", "carpet muncher", "pommie", "bender", "raunch", "damnit", "nigaboo", "crackwhore", "kooch",
             "sucked", "knockers", "raper", "poon", "dong", "pornprincess", "fudge packer", "missionary position",
             "bosom", "addicts", "boonga", "prig", "fucking", "tongethruster", "skum", "punkass", "racial",
             "wrapping men", "seks", "butchbabes", "masturbate", "slopey", "nigglings", "tight white", "unwed", "seppo",
             "boiolas", "bang (one's) box", "prince albert piercing", "fuckers", "h0m0", "fist fuck", "dickmonger",
             "hapa", "gayfuckist", "transvestite", "f u c k", "rimming", "hookah", "pansy", "f.u.c.k", "snownigger",
             "adult", "quashie", "screwing", "girl on", "goo girl", "bollox", "babes", "clitoris", "shitfull",
             "corp whore", "fuck off", "urinary", "crotchmonkey", "roundeye", "cockhead", "jigger", "beatoff", "fooker",
             "shiteater", "tonguethrust", "sadism", "chi-chi man", "mafia", "fuc", "kondums", "mo-fo", "fcuk", "labia",
             "eatme", "dinks", "whitenigger", "iblowu", "ass-jabber", "spaghettibender", "dumshit", "asscracker",
             "shagger", "breastlover", "dink", "kikes", "niglet", "lovepistol", "slant", "ganja", "cocksucks",
             "f-u-c-k", "fire", "clit", "buceta", "dominatrix", "pricks", "dickweasel", "shagging", "bombers",
             "jizjuice", "phuks", "jeez", "whorehopper", "pusse", "rectum", "babeland", "orgasmic", "suckdick",
             "assmaster", "cunillingus", "spitter", "swastika", "lesbin", "nasty", "knobead", "m45terbate", "gangbang",
             "blackout", "cumshot", "tampon", "bbw", "itch", "feltch", "pocketpool", "massa", "mutherfucking",
             "pigfucker", "crack", "s.o.b.", "figging", "hustler", "cum chugger", "beast", "nlgger", "poo",
             "donkeypunch", "intercourse", "cuntrag", "jizzim", "beef curtains", "assmucus", "cockknob", "dick head",
             "tea bagging", "footaction", "bung", "pissed off", "trannie", "sleazy", "fagtard", "phalli",
             "cockass", "areole", "cocksuka"]
